export type Dtc = { code: string; desc: string };

export const DTC_CODES: Dtc[] = [
  { code: "P0000", desc: "No trouble code stored" },
  { code: "P0100", desc: "Mass or volume air flow circuit malfunction" },
  { code: "P0101", desc: "Mass or volume air flow circuit range/performance" },
  { code: "P0102", desc: "Mass or volume air flow circuit low input" },
  { code: "P0103", desc: "Mass or volume air flow circuit high input" },
  { code: "P0110", desc: "Intake air temperature circuit malfunction" },
  { code: "P0112", desc: "Intake air temperature circuit low input" },
  { code: "P0113", desc: "Intake air temperature circuit high input" },
  { code: "P0115", desc: "Engine coolant temperature circuit malfunction" },
  { code: "P0116", desc: "Engine coolant temperature circuit range/performance" },
  { code: "P0117", desc: "Engine coolant temperature circuit low input" },
  { code: "P0118", desc: "Engine coolant temperature circuit high input" },
  { code: "P0120", desc: "Throttle/pedal position sensor A circuit malfunction" },
  { code: "P0121", desc: "Throttle/pedal position sensor A range/performance" },
  { code: "P0122", desc: "Throttle/pedal position sensor A circuit low" },
  { code: "P0123", desc: "Throttle/pedal position sensor A circuit high" },
  { code: "P0125", desc: "Insufficient coolant temp for closed loop" },
  { code: "P0128", desc: "Coolant thermostat (coolant temp below thermostat regulating temperature)" },
  { code: "P0130", desc: "O2 sensor circuit malfunction (bank 1 sensor 1)" },
  { code: "P0131", desc: "O2 sensor circuit low voltage (bank 1 sensor 1)" },
  { code: "P0132", desc: "O2 sensor circuit high voltage (bank 1 sensor 1)" },
  { code: "P0133", desc: "O2 sensor circuit slow response (bank 1 sensor 1)" },
  { code: "P0134", desc: "O2 sensor circuit no activity (bank 1 sensor 1)" },
  { code: "P0135", desc: "O2 sensor heater circuit (bank 1 sensor 1)" },
  { code: "P0136", desc: "O2 sensor circuit malfunction (bank 1 sensor 2)" },
  { code: "P0137", desc: "O2 sensor circuit low voltage (bank 1 sensor 2)" },
  { code: "P0138", desc: "O2 sensor circuit high voltage (bank 1 sensor 2)" },
  { code: "P0141", desc: "O2 sensor heater circuit (bank 1 sensor 2)" },
  { code: "P0150", desc: "O2 sensor circuit malfunction (bank 2 sensor 1)" },
  { code: "P0155", desc: "O2 sensor heater circuit (bank 2 sensor 1)" },
  { code: "P0171", desc: "System too lean (bank 1)" },
  { code: "P0172", desc: "System too rich (bank 1)" },
  { code: "P0174", desc: "System too lean (bank 2)" },
  { code: "P0175", desc: "System too rich (bank 2)" },
  { code: "P0200", desc: "Injector circuit malfunction" },
  { code: "P0201", desc: "Injector circuit malfunction — cylinder 1" },
  { code: "P0202", desc: "Injector circuit malfunction — cylinder 2" },
  { code: "P0203", desc: "Injector circuit malfunction — cylinder 3" },
  { code: "P0204", desc: "Injector circuit malfunction — cylinder 4" },
  { code: "P0205", desc: "Injector circuit malfunction — cylinder 5" },
  { code: "P0206", desc: "Injector circuit malfunction — cylinder 6" },
  { code: "P0217", desc: "Engine overtemperature condition" },
  { code: "P0220", desc: "Throttle/pedal position sensor B circuit" },
  { code: "P0230", desc: "Fuel pump primary circuit" },
  { code: "P0231", desc: "Fuel pump secondary circuit low" },
  { code: "P0232", desc: "Fuel pump secondary circuit high" },
  { code: "P0300", desc: "Random/multiple cylinder misfire detected" },
  { code: "P0301", desc: "Cylinder 1 misfire detected" },
  { code: "P0302", desc: "Cylinder 2 misfire detected" },
  { code: "P0303", desc: "Cylinder 3 misfire detected" },
  { code: "P0304", desc: "Cylinder 4 misfire detected" },
  { code: "P0305", desc: "Cylinder 5 misfire detected" },
  { code: "P0306", desc: "Cylinder 6 misfire detected" },
  { code: "P0307", desc: "Cylinder 7 misfire detected" },
  { code: "P0308", desc: "Cylinder 8 misfire detected" },
  { code: "P0316", desc: "Misfire detected on startup (first 1000 revolutions)" },
  { code: "P0320", desc: "Ignition/distributor engine speed input circuit" },
  { code: "P0325", desc: "Knock sensor 1 circuit (bank 1)" },
  { code: "P0330", desc: "Knock sensor 2 circuit (bank 2)" },
  { code: "P0335", desc: "Crankshaft position sensor A circuit" },
  { code: "P0336", desc: "Crankshaft position sensor A circuit range/performance" },
  { code: "P0340", desc: "Camshaft position sensor A circuit (bank 1)" },
  { code: "P0341", desc: "Camshaft position sensor A circuit range/performance" },
  { code: "P0351", desc: "Ignition coil A primary/secondary circuit" },
  { code: "P0352", desc: "Ignition coil B primary/secondary circuit" },
  { code: "P0353", desc: "Ignition coil C primary/secondary circuit" },
  { code: "P0354", desc: "Ignition coil D primary/secondary circuit" },
  { code: "P0400", desc: "EGR flow malfunction" },
  { code: "P0401", desc: "EGR flow insufficient" },
  { code: "P0402", desc: "EGR flow excessive" },
  { code: "P0420", desc: "Catalyst system efficiency below threshold (bank 1)" },
  { code: "P0430", desc: "Catalyst system efficiency below threshold (bank 2)" },
  { code: "P0440", desc: "EVAP system malfunction" },
  { code: "P0441", desc: "EVAP incorrect purge flow" },
  { code: "P0442", desc: "EVAP system leak detected (small leak)" },
  { code: "P0446", desc: "EVAP vent control circuit" },
  { code: "P0455", desc: "EVAP system leak detected (gross leak)" },
  { code: "P0456", desc: "EVAP system leak detected (very small leak)" },
  { code: "P0460", desc: "Fuel level sensor circuit" },
  { code: "P0463", desc: "Fuel level sensor circuit high input" },
  { code: "P0480", desc: "Cooling fan 1 control circuit" },
  { code: "P0500", desc: "Vehicle speed sensor malfunction" },
  { code: "P0505", desc: "Idle control system malfunction" },
  { code: "P0506", desc: "Idle control system RPM lower than expected" },
  { code: "P0507", desc: "Idle control system RPM higher than expected" },
  { code: "P0520", desc: "Engine oil pressure sensor/switch circuit" },
  { code: "P0522", desc: "Engine oil pressure sensor/switch low" },
  { code: "P0532", desc: "A/C refrigerant pressure sensor low" },
  { code: "P0562", desc: "System voltage low" },
  { code: "P0563", desc: "System voltage high" },
  { code: "P0600", desc: "Serial communication link" },
  { code: "P0601", desc: "Internal control module memory checksum error" },
  { code: "P0606", desc: "PCM processor fault" },
  { code: "P0627", desc: "Fuel pump A control circuit / open" },
  { code: "P0700", desc: "Transmission control system malfunction (MIL request)" },
  { code: "P0705", desc: "Transmission range sensor circuit (PRNDL input)" },
  { code: "P0715", desc: "Input/turbine speed sensor circuit" },
  { code: "P0720", desc: "Output speed sensor circuit" },
  { code: "P0730", desc: "Incorrect gear ratio" },
  { code: "P0740", desc: "Torque converter clutch circuit" },
  { code: "P0750", desc: "Shift solenoid A malfunction" },
  { code: "P0755", desc: "Shift solenoid B malfunction" },
  { code: "P0841", desc: "Transmission fluid pressure sensor A circuit range/performance" },
  { code: "P1101", desc: "MAF sensor out of self-test range" },
  { code: "P1128", desc: "Closed loop fueling not achieved" },
  { code: "P1133", desc: "O2 sensor insufficient switching (bank 1 sensor 1)" },
  { code: "P1174", desc: "Fuel trim cylinder balance bank 1" },
  { code: "P1300", desc: "Ignition coil primary circuit (manufacturer generic)" },
  { code: "P1391", desc: "CKP/CMP sensor signal intermittent" },
  { code: "P1456", desc: "EVAP system leak detected (fuel tank)" },
  { code: "P1506", desc: "Idle air control overspeed" },
  { code: "P1570", desc: "Cruise laser sensor fault" },
  { code: "P1607", desc: "PCM internal circuit malfunction" },
  { code: "P1682", desc: "Ignition 1 switch circuit 2" },
  { code: "P2181", desc: "Cooling system performance" },
  { code: "P2195", desc: "O2 sensor signal stuck lean (bank 1 sensor 1)" },
  { code: "P2196", desc: "O2 sensor signal stuck rich (bank 1 sensor 1)" },
  { code: "P2270", desc: "O2 sensor signal stuck lean (bank 1 sensor 2)" },
  { code: "P2293", desc: "Fuel pressure regulator 2 performance" },
  { code: "P2610", desc: "ECM/PCM internal engine off timer performance" },
  { code: "P2A00", desc: "O2 sensor circuit range/performance (bank 1 sensor 1)" },
  { code: "B0001", desc: "Driver frontal stage 1 deployment control" },
  { code: "B0010", desc: "Passenger frontal stage 1 deployment control" },
  { code: "B0028", desc: "Right side airbag deployment control" },
  { code: "B0050", desc: "Driver seatbelt sensor" },
  { code: "B0090", desc: "Active switch — frontal impact sensor" },
  { code: "B0100", desc: "Airbag squib circuit" },
  { code: "B1000", desc: "ECU malfunction (body control)" },
  { code: "B1325", desc: "Control module power circuit" },
  { code: "B1428", desc: "Courtesy lamp circuit" },
  { code: "B1480", desc: "Battery saver relay circuit" },
  { code: "B1681", desc: "PATS transceiver signal not received" },
  { code: "B2103", desc: "Ignition switch circuit" },
  { code: "B2477", desc: "Module configuration failure" },
  { code: "B2799", desc: "Engine immobilizer system malfunction" },
  { code: "C0035", desc: "Left front wheel speed sensor" },
  { code: "C0040", desc: "Right front wheel speed sensor" },
  { code: "C0045", desc: "Left rear wheel speed sensor" },
  { code: "C0050", desc: "Right rear wheel speed sensor" },
  { code: "C0110", desc: "Pump motor circuit" },
  { code: "C0121", desc: "Valve relay circuit" },
  { code: "C0196", desc: "Yaw rate circuit" },
  { code: "C0200", desc: "ABS enable circuit" },
  { code: "C0221", desc: "Right front wheel speed sensor circuit" },
  { code: "C0245", desc: "Wheel speed sensor frequency error" },
  { code: "C0267", desc: "Low brake fluid indicated" },
  { code: "C0278", desc: "Brake pedal position sensor" },
  { code: "C0281", desc: "Brake switch circuit" },
  { code: "C0455", desc: "Front steering position sensor" },
  { code: "C0561", desc: "System disabled information stored (ABS/TCS)" },
  { code: "C0896", desc: "Device voltage range/performance" },
  { code: "C1201", desc: "Engine control system malfunction (ABS)" },
  { code: "C1234", desc: "RR wheel speed sensor input signal missing" },
  { code: "C1241", desc: "Low battery positive voltage" },
  { code: "U0001", desc: "High speed CAN communication bus" },
  { code: "U0073", desc: "Control module communication bus off" },
  { code: "U0100", desc: "Lost communication with ECM/PCM" },
  { code: "U0101", desc: "Lost communication with TCM" },
  { code: "U0121", desc: "Lost communication with ABS module" },
  { code: "U0140", desc: "Lost communication with body control module" },
  { code: "U0151", desc: "Lost communication with restraints control module" },
  { code: "U0155", desc: "Lost communication with instrument panel cluster" },
  { code: "U0184", desc: "Lost communication with radio" },
  { code: "U0401", desc: "Invalid data received from ECM/PCM" },
  { code: "U1000", desc: "Class 2 communication malfunction" },
  { code: "U1041", desc: "Lost communication with EBCM" },
  { code: "U0107", desc: "Lost communication with throttle actuator control module" },
  { code: "U0126", desc: "Lost communication with steering angle sensor" },
  { code: "U0131", desc: "Lost communication with power steering control" },
  { code: "U0422", desc: "Invalid data received from body control module" },
  { code: "P2503", desc: "Charging system voltage low" },
  { code: "P2504", desc: "Charging system voltage high" },
  { code: "P0A80", desc: "Replace hybrid battery pack" },
  { code: "P0A7F", desc: "Hybrid battery pack deterioration" },
  { code: "P0A93", desc: "Inverter A cooling system performance" },
  { code: "P1A0C", desc: "Hybrid battery pack voltage low" },
  { code: "P2096", desc: "Post catalyst fuel trim too lean (bank 1)" },
  { code: "P2097", desc: "Post catalyst fuel trim too rich (bank 1)" },
  { code: "P2119", desc: "Throttle actuator control throttle body range/performance" },
  { code: "P2122", desc: "Throttle/pedal position sensor D circuit low" },
  { code: "P2127", desc: "Throttle/pedal position sensor E circuit low" },
  { code: "P2135", desc: "Throttle/pedal position sensor A/B voltage correlation" },
  { code: "P2138", desc: "Throttle/pedal position sensor D/E voltage correlation" },
  { code: "P2172", desc: "Throttle actuator control system sudden high air flow" },
  { code: "P219A", desc: "Bank 1 air-fuel ratio imbalance" },
  { code: "P2263", desc: "Turbocharger/supercharger boost system performance" },
  { code: "P0299", desc: "Turbocharger/supercharger underboost" },
  { code: "P0234", desc: "Turbocharger/supercharger overboost" },
  { code: "P0087", desc: "Fuel rail/system pressure too low" },
  { code: "P0088", desc: "Fuel rail/system pressure too high" },
  { code: "P0191", desc: "Fuel rail pressure sensor range/performance" },
  { code: "P0193", desc: "Fuel rail pressure sensor circuit high" },
  { code: "P06A6", desc: "Sensor reference voltage A circuit range/performance" },
  { code: "P0688", desc: "ECM/PCM power relay sense circuit" },
  { code: "P0571", desc: "Brake switch A circuit" },
  { code: "P0706", desc: "Transmission range sensor circuit range/performance" },
  { code: "P0710", desc: "Transmission fluid temperature sensor circuit" },
  { code: "P0868", desc: "Transmission fluid pressure low" },
  { code: "P2714", desc: "Pressure control solenoid D performance" },
  { code: "P2767", desc: "Input/turbine speed sensor B circuit no signal" },
];

export function searchDtc(q: string): Dtc[] {
  const s = q.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!s) return DTC_CODES.slice(0, 20);
  return DTC_CODES.filter(
    (c) => c.code.includes(s) || c.desc.toUpperCase().includes(q.trim().toUpperCase()),
  ).slice(0, 40);
}
